#!/bin/sh
while IFS= read -r -d $'\0' ARG; do
    if test "$ARG" == '--no-verify'; then
        exit 0
    fi
done < /proc/$PPID/cmdline

if git config --get custom.ignorePostCommitHook > /dev/null; then
    exit 0
fi

build_number=$(git rev-list --count HEAD)
hash=$(git rev-parse --short HEAD)
branch=$(git rev-parse --abbrev-ref HEAD)

cat <<EOL > "Namoroka/Profile Folder/chrome/version.json"
{
	"version": "1.0b1",
	"build": "$build_number",
	"hash": "$hash",
	"branch": "$branch"
}
EOL

git add "Namoroka/Profile Folder/chrome/version.json"

# Ignore next run
git config custom.ignorePostCommitHook "true"

git commit --no-verify --amend --no-edit

# Stop ignoring
git config --unset custom.ignorePostCommitHook