#!/bin/sh
while IFS= read -r -d $'\0' ARG; do
    if test "$ARG" == '--no-verify'; then
        exit 0
    fi
done < /proc/$PPID/cmdline

if git config --get custom.ignorePostCommitHook > /dev/null; then
    exit 0
fi

build_number=$(git rev-list --count HEAD)
hash=$(git rev-parse --short HEAD)
branch=$(git rev-parse --abbrev-ref HEAD)

RDF="Namoroka/install.rdf"

sed -i "s|<em:build>[^<]*</em:build>|<em:build>$build_number</em:build>|" "$RDF"
sed -i "s|<em:hash>[^<]*</em:hash>|<em:hash>$hash</em:hash>|" "$RDF"

git add "$RDF"

# Ignore next run
git config custom.ignorePostCommitHook "true"

git commit --no-verify --amend --no-edit

# Stop ignoring
git config --unset custom.ignorePostCommitHook